version: '3'

services:
  app:
    image: ojhhh/meview:latest
    ports:
      - "80:4000"
    volumes:
      - /home/ubuntu/meView_Back/.env:/usr/src/app/.env
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      DATABASE_URL: ${DATABASE_URL}