version: '3'

services:
  app:
    image: suhwani/meview:latest
    ports:
      - "80:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://suhwan_main:tnrl0258!@postgres:5432/swyp?schema=public

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: swyp
      POSTGRES_USER: suhwan_main
      POSTGRES_PASSWORD: tnrl0258!
    ports:
      - "5432:5432"
    volumes:
      - ./prisma:/app/src/db/prisma 