name: Pull Request Deploy Branch

on:
  pull_request:
    branches:
      - deploy

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH connection and clone deploy branch
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ~/.
            git clone -b deploy --single-branch https://github.com/meView/meView_Back.git
